### PR TITLE
Fix dependency package problem #3

### PR DESCRIPTION
**Pull request by Dishone**

### CODE REVIEW

**Comment by Dishone** [comment]
Hi @JohnNiang sonar-scanner has been temporarily deleted due to dependency issues. I’m not sure what package it needs on arm64, but dotnet sdk can be used.

**Review by JohnNiang — APPROVED** [review]
It works very well. Please see the screenshot below:

image

Thanks for your contribution @Dishone .

/lgtm

**Comment by JohnNiang** [comment]
/retitle Fix the problem of building DotNet agent on ARM architecture

**Comment by Dishone** [comment]
> It works very well. Please see the screenshot below:
> 
> image
> 
> Thanks for your contribution @Dishone .
> 
> /lgtm

Have a nice day. There are other areas that need improvement, please mention me.

**Review by LinuxSuRen — APPROVED** [review]
/lgtm

Everything is great! I'm just thinking about if you have any suggestions about how to choose the version of donet, when to upgrade it? It will be perfect if we can document them. Of course, we definitely can do it in the next PR.

**Comment by Dishone** [comment]
> /lgtm
> 
> Everything is great! I'm just thinking about if you have any suggestions about how to choose the version of donet, when to upgrade it? It will be perfect if we can document them. Of course, we definitely can do it in the next PR.
.Net 6 will be available on November 9,I think I can provide support soon.

**Comment by Dishone** [comment]
> > /lgtm
> > Everything is great! I'm just thinking about if you have any suggestions about how to choose the version of donet, when to upgrade it? It will be perfect if we can document them. Of course, we definitely can do it in the next PR.
> 
> .Net 6 will be available on November 9,I think I can provide support soon.

I am using my custom .net6 agent to build many images. For the old version, the performance of .net6 containers has improved significantly.

**Comment by LinuxSuRen** [comment]
I don't have any experience with donet. Thanks for that.

**Comment by Dishone** [comment]
That's ok. I will pull requests soon.

**Pull request merged**
