### PR TITLE
Use a specified version of base image instead the latest

### PR DESCRIPTION
**Pull request by LinuxSuRen**

### CODE REVIEW

**Comment by JohnNiang** [comment]
If do that, we have to build and push `base` docker image before others.

**Comment by LinuxSuRen** [comment]
> If do that, we have to build and push `base` docker image before others.

Correct. Please see also the following screenshot:

image

https://github.com/kubesphere/devops-agent/actions/runs/873446599

**Comment by JohnNiang** [comment]
> If do that, we have to build and push `base` docker image before others.

Before building others, we have to change docker image of base of them.

**Comment by LinuxSuRen** [comment]
> Before building others, we have to change kubespheredev/builder-base:v3.1.0 in Dockerfile.

I didn't get your point. The reason why I create this PR because using the latest base image will lead unpredicted situation.

**Comment by JohnNiang** [comment]
> > Before building others, we have to change kubespheredev/builder-base:v3.1.0 in Dockerfile.
> 
> I didn't get your point. The reason why I create this PR because using the latest base image will lead unpredicted situation.

If we build agents separately, that's a great point for stable. In fact, agents except `base` base on `base` building, so it's no problem to use latest version of base image in Dockerfile.

**Comment by LinuxSuRen** [comment]
> If we build agents separately, that's a great point for stable. In fact, agents except base base on base building, so it's no problem to use latest version of base image in Dockerfile.

What if someone wants to build an old release instead of the latest code base? For example, let's assume the user wants to build v1.0, then he will get the wrong base image for the agents.

**Comment by JohnNiang** [comment]
> > If we build agents separately, that's a great point for stable. In fact, agents except base base on base building, so it's no problem to use latest version of base image in Dockerfile.
> 
> What if someone wants to build an old release instead of the latest code base? For example, let's assume the user wants to build v1.0, then he will get the wrong base image for the agents.

Whether we specify the version or not, he/she has to modify it according to his/her needs.

**Comment by LinuxSuRen** [comment]
> Whether we specify the version or not, he/she has to modify it according to his/her needs.

I don't think so. Users might just want to build, and don't change the code base.

**Comment by JohnNiang** [comment]
> > Whether we specify the version or not, he/she has to modify it according to his/her needs.
> 
> I don't think so. Users might just want to build, and don't change the code base.

I don't think we can solve the problem by specifying the version. Also, this increases maintenance costs.

**Comment by JohnNiang** [comment]
I get your point now.

**Comment by JohnNiang** [comment]
There's a new problem that we have to change image version manually when we release a new one.

**Comment by LinuxSuRen** [comment]
No worries. There'e no big deal to change the base image version. And I think we should change it manually instead of automatically. Because we don't have a final solution to make sure the quality of the base image.

**Pull request merged**
