### PR TITLE
Add the missing python image declaration in README

### LINKED ISSUE #35: Add the missing python image declaration in README
Hi @yuezhuangshi , thanks for your contriubution. 

I think we are missing docker image declaration in `README.md`. Can you help us add it in another PR?

_Originally posted by @JohnNiang in https://github.com/kubesphere/devops-agent/issues/31#issuecomment-902396668_

### PR DESCRIPTION
**Pull request by yuezhuangshi**
fix #35

### CODE REVIEW

**Comment by yuezhuangshi** [comment]
Hi @JohnNiang , I have added the missing python image declaration in README.

**Comment by JohnNiang** [comment]
Thanks for your quick response. We are inspecting the missing `kubespheredev/builder-python` which is not found in <https://hub.docker.com/u/kubespheredev>.

**Comment by yuezhuangshi** [comment]
> Thanks for your quick response. We are inspecting the missing docker image `kubespheredev/builder-python` which is not found in https://hub.docker.com/u/kubespheredev.
Something went wrong in [action](https://github.com/kubesphere/devops-agent/runs/3377943585): `ERROR: authorization status: 401: authorization failed`, It seems that there is a problem with the repository authentication when pushing the image and I don't know why.

**Comment by JohnNiang** [comment]
@yuezhuangshi It's not your problem. I have asked the [community](https://github.com/kubesphere/community) to create corresponding docker image. Please see <https://github.com/kubesphere/community/issues/360>.

**Review by LinuxSuRen — APPROVED** [review]
/lgtm

**Pull request merged**
