### PR TITLE
Fix no package dotnet-sdk-5.0 available.

### PR DESCRIPTION
**Pull request by Dishone**
This has been verified by me. Everything is normal when it is built locally

### CODE REVIEW

**Comment by JohnNiang** [comment]
It's so strange when I build the .DotNet agent in Gitpod, please see the screenshot:

image

**Comment by JohnNiang** [comment]
If you want to have a try of Gitpod for testing, please forward to https://gitpod.io/#https://github.com/kubesphere/devops-agent.

**Comment by Dishone** [comment]
> If you want to have a try of Gitpod for testing, please forward to https://gitpod.io/#https://github.com/kubesphere/devops-agent.

I think it's all normal This image was successfully built

**Comment by Dishone** [comment]
@JohnNiang https://github.com/kubesphere/devops-agent/actions/runs/1398472523 I think this error may be caused by regional network issues. The packages-microsoft-prod repository is not enabled.

**Comment by JohnNiang** [comment]
@Dishone I just triggered a build of my Pull Request #51, we could wait for the result of https://github.com/kubesphere/devops-agent/runs/4104090752?check_suite_focus=true.

**Comment by JohnNiang** [comment]
Hi @Dishone , I found that the build on AMD64 is perfect,  but unfortunate on ARM64.

image
image

**Comment by Dishone** [comment]
@JohnNiang Package manager installs are only supported on the x64 architecture. Other architectures, such as ARM, must install .NET by some other means such as with Snap, an installer script, or through a manual binary installation.
https://docs.microsoft.com/en-us/dotnet/core/install/linux-centos

**Pull request closed without merging**
